language: generic
sudo: required
services:
  - docker

before-install:
  - docker build -t joeattah1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joeattah1/docker-react npm run test
